name: 'Generate Matrix from Changed Files'
description: 'Generates a matrix for GitHub Actions based on changed files'
inputs:
  all_changed_files:
    description: 'All changed files'
    required: true
  path_prefix:
    description: 'Path prefix to strip from changed files'
    required: false
    default: ''
outputs:
  matrix:
    description: 'Matrix for GitHub Actions'
runs:
  using: 'node12'
  main: 'action/index.js'